M48
; DRILL file {KiCad (7.0.0)} date Fri Jun  2 20:54:25 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-02T20:54:25-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X66.929Y-42.545
X66.929Y-64.135
X125.349Y-42.545
X125.349Y-64.135
T0
M30
